name: daily-metrics

on:
  workflow_dispatch:
  push:
  schedule:
    - cron: "0 0 * * *"

jobs:   
  stats:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    environment:
      name: production
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          committer_branch: metrics
          committer_message: "build: update `${filename}`"

          filename: stats.svg
          template: classic
          base: header, activity, community
          config_timezone: America/Los_Angeles

  calendar:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    environment:
      name: production
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          committer_branch: metrics
          committer_message: "build: update `${filename}`"

          filename: calendar.svg
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year

  languages:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    environment:
      name: production
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          committer_branch: metrics
          committer_message: "build: update `${filename}`"

          filename: languages.svg
          base: ""
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_analysis_timeout_repositories: 7.5
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_limit: 8
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%

  topics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    environment:
      name: production
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          committer_branch: metrics
          committer_message: "build: update `${filename}`"

          filename: topics.svg
          base: ""
          plugin_topics: yes
          plugin_topics_limit: 0
          plugin_topics_mode: icons
          plugin_topics_sort: stars
